# Site settings
title: Metatavu Oy
email: info@metatavu.fi
url: https://metatavu.fi
description: "Metatavu Oy is a Finnish software company and we are specialized in high quality software and open source solutions."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Metatavu Oy

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: bitbucket
    url: https://bitbucket.org/metatavu/
  - title: github
    url: https://github.com/Metatavu

# Build settings
markdown: kramdown
permalink: pretty
